name: Swift nightly build

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-nightly
  cancel-in-progress: true

jobs:
  macOS:
    runs-on: macos-15
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: SPM tests
      run: swift test
  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        image: ['nightly-focal', 'nightly-jammy', 'nightly-amazonlinux2']
    container:
      image: swiftlang/swift:${{ matrix.image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Test
      run: |
        swift test
